packages:
  - "pnpm-global"
  - "lib"
  - "ui"
  - "eicoop"
  - "eicoop2"
  - "wasmegg/_home"
  - "wasmegg/artifact-explorer"
  - "wasmegg/artifact-sandbox"
  - "wasmegg/consumption-sheet"
  - "wasmegg/enlightenment"
  - "wasmegg/events"
  - "wasmegg/inventory-visualizer"
  - "wasmegg/loot-simulator"
  - "wasmegg/mission-list"
  - "wasmegg/past-contracts"
  - "wasmegg/past-contracts-eicoop2"
  - "wasmegg/proto-explorer"
  - "wasmegg/researches"
  - "wasmegg/rockets-tracker"
  - "wasmegg/smart-assistant"
  - "wasmegg/shell-company"
  - "wasmegg/eggs-laid"
