[[redirects]]
  from = "/api/*"
  to = "https://www.auxbrain.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[build]
  publish = "dist/"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
