export const donors = [
  "3Omac",
  "Adriannosaurus",
  "ahoff",
  "Anonymous",
  "bbbb1121",
  "cneal",
  "Dandy",
  "dchester",
  "DhrMekmek",
  "dmarshall",
  "ejones",
  "evasion-funky0w",
  "Feather_1",
  "Garrok",
  "Greenz",
  "Jammin",
  "JassmSa",
  "jbienkens",
  "kjkawa",
  "kok-kakarott",
  "Lightcraftsman20",
  "lorgle",
  "mav",
  "milky 🍼",
  "Menno",
  "mifn humorous shiver",
  "Minty",
  "Owen#0805",
  "sgilliam",
  "shen",
  "synthparadox",
  "Teufelhunden",
  "TortugaSheriff",
  "Vijay",
  "WorldlyRedNeck",
];
