export const donors = [
  '3Omac',
  'Adriannosaurus',
  'ahoff',
  'Anonymous',
  'BananaJS',
  'bbbb1121',
  'budvugger',
  'cneal',
  'Dandy',
  'dchester',
  'DhrMekmek',
  'Divemistress',
  'dmarshall',
  'ejones',
  'evasion-funky0w',
  'Feather_1',
  'Garrok',
  'Gomero',
  'Greenz',
  'grim 🐳',
  'Jammin',
  'JassmSa',
  'jbienkens',
  'kjkawa',
  'kok-kakarott',
  'Lightcraftsman20',
  'lorgle',
  'mav',
  'Menno',
  'mifn humorous shiver',
  'milky 🍼',
  'Minty',
  'Owen#0805',
  'Quail',
  'sentient_ent 🦥',
  'sgilliam',
  'shen',
  'synthparadox',
  'Teufelhunden',
  'TortugaSheriff',
  'Vijay',
  'WorldlyRedNeck',
  'nick_drake',
  'leeroyjenkees',
];
