type FixedLengthArray<T, L extends number> = [T, ...T[]] & { length: L };

export const donors: FixedLengthArray<string, 22> = [
  "Adriannosaurus",
  "Anonymous",
  "bbbb1121",
  "cneal",
  "dchester",
  "DhrMekmek",
  "dmarshall",
  "evasion-funky0w",
  "Garrok",
  "Jammin",
  "jbienkens",
  "kjkawa",
  "kok-kakarott",
  "lorgle",
  "Menno",
  "mlyons",
  "Owen#0805",
  "sgilliam",
  "shen",
  "synthparadox",
  "Vijay",
  "WorldlyRedNeck",
];
