<template>
  <main class="max-w-6xl w-full px-4 xl:px-0 mx-auto my-6">
    <h1 class="mx-4 mt-4 mb-2 text-center text-lg leading-6 font-medium text-gray-900">
      Rockets tracker <span class="whitespace-nowrap">legendary study report</span>
    </h1>
    <div class="my-2">
      <p class="text-sm">
        Reports for the
        <a
          href="https://wasmegg-carpet.netlify.app/rockets-tracker/"
          target="_blank"
          class="text-blue-500 hover:text-blue-600"
          >rockets tracker</a
        >
        legendary study are posted here. You can view historical reports and compare reports to see
        how legendary ownership of the player base has evolved over time. Keep in mind that data
        posted here are subject to selection bias; players who use the rockets tracker and opt in to
        the study are likely more avid than the majority of the Egg, Inc. player base at large.
      </p>
      <p class="text-sm mt-1">
        You can opt into the study yourself at
        <a
          href="https://wasmegg-carpet.netlify.app/rockets-tracker/"
          target="_blank"
          class="text-blue-500 hover:text-blue-600"
          >wasmegg-carpet.netlify.app/rockets-tracker</a
        >, in which case a hash of your ID and your current backup will be
        collected. The study is open source; the code can be found <a
          href="https://github.com/Brosssh/legendary-study-3.0"
          target="_blank"
          class="text-blue-500 hover:text-blue-600"
          >here</a>.
      </p>
      <p class="text-sm mt-5">
        What is the difference between this app and the <a
          href="https://legendary-study.netlify.app/"
          target="_blank"
          class="text-blue-500 hover:text-blue-600"
          >previous one</a
        > by mk2? The reports generated by the previous study were limited to 20 legendarys since people with more 
        than that were considered, at the time, certain cheaters. Now there are plenty of legit people with more then 
        20 legendarys and that's why this study.
      </p>
      <p class="text-sm mt-5">
        Note: starting from the 2025-01-28, the ZLC record refer to the "new" ship, Atreggies Henliner.
      </p>
    </div>
    <router-view />
  </main>
</template>
