name: build-wasmegg
on:
  push:
    paths:
      - pnpm-lock.yaml
      - 'wasmegg/**'
      - 'ui/**'
      - 'lib/**'
      - 'periodicals/*'
      - 'periodicals/data/*'
      - '!periodicals/data/contracts.json'
      - '!periodicals/data/seasoncontracts.json'
      - 'protobuf/ei.proto'
  pull_request:
    types: [opened, synchronize, edited, reopened]
    paths:
      - 'lib/**'
      - 'ui/**'
      - 'wasmegg/**'
      - 'periodicals/*'
      - 'periodicals/data/*'
  workflow_dispatch:

permissions:
  contents: read
  #schedule:
  # Regenerate every day to incorporate updated mission outcome data.
  # Cron moved to cloudflare worker for more reliable timing
  # - cron: '30 4 * * *'
jobs:
  # No TS type checking for faster deployment.
  wasmegg-fastbuild:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
    defaults:
      run:
        working-directory: wasmegg
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-wasmegg-deps
      - uses: ./.github/actions/setup-pnpm-node
        with:
          cache-dependency-path: |
            pnpm-lock.yaml
            pnpm-global/5/pnpm-lock.yaml
      - name: Cache netlify-headers-expander
        uses: actions/cache@v5
        with:
          path: wasmegg/netlify-headers-expander
          key: netlify-headers-expander-1.0.0
      - name: Do other preparations
        run: |
          ../action-scripts/prepare
      - name: Build lib
        working-directory: lib
        run: |
          make init
          make
      - name: Initialize dependencies
        run: |
          make init -j1
      - name: Build
        run: |
          make -j2 fastbuild
        env:
          EIAPI_TOKEN: ${{ secrets.EIAPI_TOKEN }}
      - uses: ./.github/actions/netlify-deploy
        working-directory: wasmegg
        with:
          dist-dir: wasmegg/dist
          site-id: ${{ secrets.NETLIFY_WASMEGG_SITE_ID }}
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  # With TS type checking.
  wasmegg-fullbuild:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wasmegg
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-wasmegg-deps
      - uses: ./.github/actions/setup-pnpm-node
        with:
          cache-dependency-path: |
            pnpm-lock.yaml
            pnpm-global/5/pnpm-lock.yaml
      - name: Cache netlify-headers-expander
        uses: actions/cache@v5
        with:
          path: wasmegg/netlify-headers-expander
          key: netlify-headers-expander-1.0.0
      - name: Do other preparations
        run: |
          ../action-scripts/prepare
      - name: Build lib
        working-directory: lib
        run: |
          make init
          make
      - name: Initialize dependencies
        run: |
          make init -j1
      - name: Build
        run: |
          make -j2
        env:
          EIAPI_TOKEN: ${{ secrets.EIAPI_TOKEN }}
