name: update-loot-data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
jobs:
  update:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wasmegg/artifact-explorer
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
      - name: Update Loot Data
        run: |
          git pull --rebase
          make data
      - name: Commit, push changes, and possibly trigger new build
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add src/lib/loot.json
          git diff --cached --quiet || {
            git commit -m 'artifact-explorer: update loot data (from GitHub Actions)'
            git push
          }
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
